version: '3'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
#   for restarting server on changes while developing
    restart: always
    command: npm run dev
    volumes:
        - ./backend:/backend
    environment:
      NODE_ENV: development
#    to check in node app how we start server (threw docker-compose ore not)
      COMPOSE: "true"
    env_file:
      - ./backend/.env-development
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

  postgres:
    image: postgres
    env_file:
      - ./backend/.env-development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ./backend/.env-development
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: overlay

